# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/alex/Projects/parts localization"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/alex/Projects/parts localization"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alex/Projects/parts localization/CMakeFiles" "/Users/alex/Projects/parts localization/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alex/Projects/parts localization/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parts_localization

# Build rule for target.
parts_localization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parts_localization
.PHONY : parts_localization

# fast build rule for target.
parts_localization/fast:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/build
.PHONY : parts_localization/fast

edgesChns.o: edgesChns.cpp.o

.PHONY : edgesChns.o

# target to build an object file
edgesChns.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesChns.cpp.o
.PHONY : edgesChns.cpp.o

edgesChns.i: edgesChns.cpp.i

.PHONY : edgesChns.i

# target to preprocess a source file
edgesChns.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesChns.cpp.i
.PHONY : edgesChns.cpp.i

edgesChns.s: edgesChns.cpp.s

.PHONY : edgesChns.s

# target to generate assembly for a file
edgesChns.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesChns.cpp.s
.PHONY : edgesChns.cpp.s

edgesDetect.o: edgesDetect.cpp.o

.PHONY : edgesDetect.o

# target to build an object file
edgesDetect.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetect.cpp.o
.PHONY : edgesDetect.cpp.o

edgesDetect.i: edgesDetect.cpp.i

.PHONY : edgesDetect.i

# target to preprocess a source file
edgesDetect.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetect.cpp.i
.PHONY : edgesDetect.cpp.i

edgesDetect.s: edgesDetect.cpp.s

.PHONY : edgesDetect.s

# target to generate assembly for a file
edgesDetect.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetect.cpp.s
.PHONY : edgesDetect.cpp.s

edgesDetectMex.o: edgesDetectMex.cpp.o

.PHONY : edgesDetectMex.o

# target to build an object file
edgesDetectMex.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetectMex.cpp.o
.PHONY : edgesDetectMex.cpp.o

edgesDetectMex.i: edgesDetectMex.cpp.i

.PHONY : edgesDetectMex.i

# target to preprocess a source file
edgesDetectMex.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetectMex.cpp.i
.PHONY : edgesDetectMex.cpp.i

edgesDetectMex.s: edgesDetectMex.cpp.s

.PHONY : edgesDetectMex.s

# target to generate assembly for a file
edgesDetectMex.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesDetectMex.cpp.s
.PHONY : edgesDetectMex.cpp.s

edgesNmsMex.o: edgesNmsMex.cpp.o

.PHONY : edgesNmsMex.o

# target to build an object file
edgesNmsMex.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesNmsMex.cpp.o
.PHONY : edgesNmsMex.cpp.o

edgesNmsMex.i: edgesNmsMex.cpp.i

.PHONY : edgesNmsMex.i

# target to preprocess a source file
edgesNmsMex.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesNmsMex.cpp.i
.PHONY : edgesNmsMex.cpp.i

edgesNmsMex.s: edgesNmsMex.cpp.s

.PHONY : edgesNmsMex.s

# target to generate assembly for a file
edgesNmsMex.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/edgesNmsMex.cpp.s
.PHONY : edgesNmsMex.cpp.s

gadgets.o: gadgets.cpp.o

.PHONY : gadgets.o

# target to build an object file
gadgets.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/gadgets.cpp.o
.PHONY : gadgets.cpp.o

gadgets.i: gadgets.cpp.i

.PHONY : gadgets.i

# target to preprocess a source file
gadgets.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/gadgets.cpp.i
.PHONY : gadgets.cpp.i

gadgets.s: gadgets.cpp.s

.PHONY : gadgets.s

# target to generate assembly for a file
gadgets.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/gadgets.cpp.s
.PHONY : gadgets.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/main.cpp.s
.PHONY : main.cpp.s

parts_localization.o: parts_localization.cpp.o

.PHONY : parts_localization.o

# target to build an object file
parts_localization.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization.cpp.o
.PHONY : parts_localization.cpp.o

parts_localization.i: parts_localization.cpp.i

.PHONY : parts_localization.i

# target to preprocess a source file
parts_localization.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization.cpp.i
.PHONY : parts_localization.cpp.i

parts_localization.s: parts_localization.cpp.s

.PHONY : parts_localization.s

# target to generate assembly for a file
parts_localization.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization.cpp.s
.PHONY : parts_localization.cpp.s

parts_localization_main.o: parts_localization_main.cpp.o

.PHONY : parts_localization_main.o

# target to build an object file
parts_localization_main.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization_main.cpp.o
.PHONY : parts_localization_main.cpp.o

parts_localization_main.i: parts_localization_main.cpp.i

.PHONY : parts_localization_main.i

# target to preprocess a source file
parts_localization_main.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization_main.cpp.i
.PHONY : parts_localization_main.cpp.i

parts_localization_main.s: parts_localization_main.cpp.s

.PHONY : parts_localization_main.s

# target to generate assembly for a file
parts_localization_main.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/parts_localization_main.cpp.s
.PHONY : parts_localization_main.cpp.s

tools/ConvTri.o: tools/ConvTri.cpp.o

.PHONY : tools/ConvTri.o

# target to build an object file
tools/ConvTri.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/ConvTri.cpp.o
.PHONY : tools/ConvTri.cpp.o

tools/ConvTri.i: tools/ConvTri.cpp.i

.PHONY : tools/ConvTri.i

# target to preprocess a source file
tools/ConvTri.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/ConvTri.cpp.i
.PHONY : tools/ConvTri.cpp.i

tools/ConvTri.s: tools/ConvTri.cpp.s

.PHONY : tools/ConvTri.s

# target to generate assembly for a file
tools/ConvTri.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/ConvTri.cpp.s
.PHONY : tools/ConvTri.cpp.s

tools/convConst.o: tools/convConst.cpp.o

.PHONY : tools/convConst.o

# target to build an object file
tools/convConst.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/convConst.cpp.o
.PHONY : tools/convConst.cpp.o

tools/convConst.i: tools/convConst.cpp.i

.PHONY : tools/convConst.i

# target to preprocess a source file
tools/convConst.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/convConst.cpp.i
.PHONY : tools/convConst.cpp.i

tools/convConst.s: tools/convConst.cpp.s

.PHONY : tools/convConst.s

# target to generate assembly for a file
tools/convConst.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/convConst.cpp.s
.PHONY : tools/convConst.cpp.s

tools/gradient.o: tools/gradient.cpp.o

.PHONY : tools/gradient.o

# target to build an object file
tools/gradient.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradient.cpp.o
.PHONY : tools/gradient.cpp.o

tools/gradient.i: tools/gradient.cpp.i

.PHONY : tools/gradient.i

# target to preprocess a source file
tools/gradient.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradient.cpp.i
.PHONY : tools/gradient.cpp.i

tools/gradient.s: tools/gradient.cpp.s

.PHONY : tools/gradient.s

# target to generate assembly for a file
tools/gradient.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradient.cpp.s
.PHONY : tools/gradient.cpp.s

tools/gradientMex.o: tools/gradientMex.cpp.o

.PHONY : tools/gradientMex.o

# target to build an object file
tools/gradientMex.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradientMex.cpp.o
.PHONY : tools/gradientMex.cpp.o

tools/gradientMex.i: tools/gradientMex.cpp.i

.PHONY : tools/gradientMex.i

# target to preprocess a source file
tools/gradientMex.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradientMex.cpp.i
.PHONY : tools/gradientMex.cpp.i

tools/gradientMex.s: tools/gradientMex.cpp.s

.PHONY : tools/gradientMex.s

# target to generate assembly for a file
tools/gradientMex.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/gradientMex.cpp.s
.PHONY : tools/gradientMex.cpp.s

tools/imPadMex.o: tools/imPadMex.cpp.o

.PHONY : tools/imPadMex.o

# target to build an object file
tools/imPadMex.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/imPadMex.cpp.o
.PHONY : tools/imPadMex.cpp.o

tools/imPadMex.i: tools/imPadMex.cpp.i

.PHONY : tools/imPadMex.i

# target to preprocess a source file
tools/imPadMex.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/imPadMex.cpp.i
.PHONY : tools/imPadMex.cpp.i

tools/imPadMex.s: tools/imPadMex.cpp.s

.PHONY : tools/imPadMex.s

# target to generate assembly for a file
tools/imPadMex.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/imPadMex.cpp.s
.PHONY : tools/imPadMex.cpp.s

tools/rgbConvertMex.o: tools/rgbConvertMex.cpp.o

.PHONY : tools/rgbConvertMex.o

# target to build an object file
tools/rgbConvertMex.cpp.o:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/rgbConvertMex.cpp.o
.PHONY : tools/rgbConvertMex.cpp.o

tools/rgbConvertMex.i: tools/rgbConvertMex.cpp.i

.PHONY : tools/rgbConvertMex.i

# target to preprocess a source file
tools/rgbConvertMex.cpp.i:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/rgbConvertMex.cpp.i
.PHONY : tools/rgbConvertMex.cpp.i

tools/rgbConvertMex.s: tools/rgbConvertMex.cpp.s

.PHONY : tools/rgbConvertMex.s

# target to generate assembly for a file
tools/rgbConvertMex.cpp.s:
	$(MAKE) -f CMakeFiles/parts_localization.dir/build.make CMakeFiles/parts_localization.dir/tools/rgbConvertMex.cpp.s
.PHONY : tools/rgbConvertMex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... parts_localization"
	@echo "... edgesChns.o"
	@echo "... edgesChns.i"
	@echo "... edgesChns.s"
	@echo "... edgesDetect.o"
	@echo "... edgesDetect.i"
	@echo "... edgesDetect.s"
	@echo "... edgesDetectMex.o"
	@echo "... edgesDetectMex.i"
	@echo "... edgesDetectMex.s"
	@echo "... edgesNmsMex.o"
	@echo "... edgesNmsMex.i"
	@echo "... edgesNmsMex.s"
	@echo "... gadgets.o"
	@echo "... gadgets.i"
	@echo "... gadgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parts_localization.o"
	@echo "... parts_localization.i"
	@echo "... parts_localization.s"
	@echo "... parts_localization_main.o"
	@echo "... parts_localization_main.i"
	@echo "... parts_localization_main.s"
	@echo "... tools/ConvTri.o"
	@echo "... tools/ConvTri.i"
	@echo "... tools/ConvTri.s"
	@echo "... tools/convConst.o"
	@echo "... tools/convConst.i"
	@echo "... tools/convConst.s"
	@echo "... tools/gradient.o"
	@echo "... tools/gradient.i"
	@echo "... tools/gradient.s"
	@echo "... tools/gradientMex.o"
	@echo "... tools/gradientMex.i"
	@echo "... tools/gradientMex.s"
	@echo "... tools/imPadMex.o"
	@echo "... tools/imPadMex.i"
	@echo "... tools/imPadMex.s"
	@echo "... tools/rgbConvertMex.o"
	@echo "... tools/rgbConvertMex.i"
	@echo "... tools/rgbConvertMex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

